# Generated by Django 3.0.6 on 2021-10-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inclusao', models.DateField()),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
